# Generated by Django 2.1.4 on 2019-01-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Типа поставок может меняться от применения', max_length=100, verbose_name='Тип поставки')),
                ('short', models.CharField(help_text='Краткое имя', max_length=5, unique=True, verbose_name='Короткое имя')),
                ('status', models.CharField(choices=[('inn', 'Входящая'), ('out', 'Исходящая'), ('int', 'Внутренняя')], default='Входящая', max_length=20, verbose_name='Направление')),
                ('erp_link', models.CharField(blank=True, help_text='Ссылка на тип поставки в ERP истемах', max_length=5, null=True, verbose_name='Тип поставки ERP')),
            ],
        ),
    ]
