# Generated by Django 2.1.4 on 2019-01-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytype',
            name='name',
            field=models.CharField(help_text='Типа поставок может меняться от применения', max_length=100, verbose_name='Имя'),
        ),
    ]
