# Generated by Django 2.1.4 on 2019-01-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20190121_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytype',
            name='erp_link',
            field=models.CharField(blank=True, help_text='Ссылка на тип поставки в ERP истемах, можно использовать как имя сервиса', max_length=40, null=True, verbose_name='Тип поставки ERP'),
        ),
    ]
