# Generated by Django 2.1.4 on 2019-01-21 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wmsbase', '0011_warehouseobjecttype_lowest'),
        ('delivery', '0003_auto_20190121_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Номер поставки из Омни', max_length=100, verbose_name='Номер поставки Омни')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('creator', models.ForeignKey(on_delete=models.SET('Юзер удален'), related_name='createHead', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updater', models.ForeignKey(on_delete=models.SET('Юзер удален'), related_name='updateHead', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_number', models.IntegerField(verbose_name='Номер позиции в поставке')),
                ('value', models.DecimalField(decimal_places=5, max_digits=10, max_length=50, verbose_name='Количество')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('creator', models.ForeignKey(on_delete=models.SET('Юзер удален'), related_name='createPosition', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.DeliveryHead', verbose_name='Поставка')),
                ('material', models.ForeignKey(on_delete=models.SET('Материал удален'), to='wmsbase.Material', verbose_name='Материал')),
                ('updater', models.ForeignKey(on_delete=models.SET('Юзер удален'), related_name='updatePosition', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='deliveryposition',
            unique_together={('creator', 'updater')},
        ),
    ]
