# Generated by Django 2.1.4 on 2019-01-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20190121_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryhead',
            name='partner',
            field=models.CharField(blank=True, max_length=100, verbose_name='Партнер'),
        ),
    ]
