# Generated by Django 2.1.4 on 2019-01-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_deliveryhead_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryhead',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата Изменения'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryposition',
            unique_together=set(),
        ),
    ]
