# Generated by Django 2.1.4 on 2019-02-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20190131_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryhead',
            name='_positions',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество позиций'),
        ),
    ]
