# Generated by Django 2.1.4 on 2019-02-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_deliveryhead__positions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryhead',
            old_name='_positions',
            new_name='positions',
        ),
    ]
