# Generated by Django 2.1.4 on 2019-02-06 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wmsbase', '0011_warehouseobjecttype_lowest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0008_auto_20190204_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPositionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Типа поставок может меняться от применения', max_length=100, verbose_name='Имя')),
                ('short', models.CharField(help_text='Краткое имя', max_length=5, unique=True, verbose_name='Короткое имя')),
                ('erp_link', models.CharField(blank=True, help_text='Ссылка на тип позиции поставки в ERP истемах, можно использовать как имя сервиса', max_length=40, null=True, verbose_name='Тип поставки ERP')),
            ],
        ),
        migrations.CreateModel(
            name='LogisticDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=5, max_digits=10, max_length=50, verbose_name='Количество')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('bu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsbase.BussinesUnit', verbose_name='Бизнес юнит')),
                ('creator', models.ForeignKey(on_delete=models.SET('Юзер удален'), related_name='creatorLogDoc', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryhead',
            name='delivery_type',
            field=models.ForeignKey(blank=True, default=None, on_delete=models.SET('Тип удален'), to='delivery.DeliveryType', verbose_name='Тип поставки'),
        ),
        migrations.AddField(
            model_name='deliveryposition',
            name='delivery_position_type',
            field=models.ForeignKey(blank=True, default=None, on_delete=models.SET('Тип удален'), to='delivery.DeliveryType', verbose_name='Тип позиции поставки'),
        ),
        migrations.AlterField(
            model_name='deliveryposition',
            name='creator',
            field=models.ForeignKey(on_delete=models.SET('Юзер удален'), related_name='createDeliveryPos', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='deliveryposition',
            name='updater',
            field=models.ForeignKey(on_delete=models.SET('Юзер удален'), related_name='updateDeliveryPos', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='logisticdoc',
            name='delivery',
            field=models.ForeignKey(blank=True, on_delete=models.SET('Поставка удалена'), to='delivery.DeliveryHead', verbose_name='Документ основание'),
        ),
        migrations.AddField(
            model_name='logisticdoc',
            name='delivery_pos',
            field=models.ForeignKey(blank=True, on_delete=models.SET('Поставка удалена'), to='delivery.DeliveryPosition', verbose_name='Документ основание'),
        ),
        migrations.AddField(
            model_name='logisticdoc',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsbase.Client', verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='logisticdoc',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=models.SET('ЕИ Удалена'), to='wmsbase.Uom', verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='logisticdoc',
            name='updater',
            field=models.ForeignKey(on_delete=models.SET('Юзер удален'), related_name='updaterLogDoc', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
    ]
