# Generated by Django 2.1.4 on 2019-02-06 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_auto_20190206_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryhead',
            name='delivery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.DeliveryType', verbose_name='Тип поставки'),
        ),
        migrations.AlterField(
            model_name='deliveryhead',
            name='number',
            field=models.CharField(blank=True, help_text='Номер поставки из Омни', max_length=100, verbose_name='Номер поставки ERP'),
        ),
    ]
