# Generated by Django 2.1.4 on 2019-02-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_auto_20190206_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryhead',
            name='delivery_type',
            field=models.ForeignKey(blank=True, on_delete=models.SET('Тип удален'), to='delivery.DeliveryType', verbose_name='Тип поставки'),
        ),
        migrations.AlterField(
            model_name='deliveryhead',
            name='number',
            field=models.CharField(blank=True, help_text='Номер поставки из внешней системы', max_length=100, verbose_name='Номер поставки ERP'),
        ),
    ]
