# Generated by Django 2.1.4 on 2019-02-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_auto_20190206_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryhead',
            name='delivery_type',
            field=models.ForeignKey(blank=True, on_delete=models.SET('Тип удален'), to='delivery.DeliveryType', verbose_name='Тип поставки'),
        ),
    ]
