# Generated by Django 2.1.4 on 2019-02-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_auto_20190206_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryhead',
            name='delivery_type',
        ),
    ]
