# Generated by Django 2.1.4 on 2019-02-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_remove_deliveryhead_delivery_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryposition',
            name='delivery_position_type',
        ),
        migrations.DeleteModel(
            name='DeliveryType',
        ),
    ]
