# Generated by Django 2.1.4 on 2019-02-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_auto_20190206_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Типа поставок может меняться от применения', max_length=100, verbose_name='Имя')),
                ('short', models.CharField(help_text='Краткое имя', max_length=5, unique=True, verbose_name='Короткое имя')),
                ('status', models.CharField(choices=[('inn', 'Входящая'), ('out', 'Исходящая'), ('int', 'Внутренняя')], default='Входящая', max_length=20, verbose_name='Направление')),
                ('erp_link', models.CharField(blank=True, help_text='Ссылка на тип поставки в ERP истемах, можно использовать как имя сервиса', max_length=40, null=True, verbose_name='Тип поставки ERP')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryhead',
            name='delivery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Тип удален'), to='delivery.DeliveryType', verbose_name='Тип поставки'),
        ),
        migrations.AddField(
            model_name='deliveryposition',
            name='delivery_position_type',
            field=models.ForeignKey(blank=True, default=None, on_delete=models.SET('Тип удален'), to='delivery.DeliveryType', verbose_name='Тип позиции поставки'),
        ),
    ]
