# Generated by Django 2.1.4 on 2019-02-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_remove_deliveryhead_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryhead',
            name='delivery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Тип удален'), to='delivery.DeliveryType', verbose_name='Тип поставки'),
        ),
    ]
