# Generated by Django 2.1.4 on 2019-02-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0021_auto_20190206_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryposition',
            name='delivery_position_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET('Тип удален'), to='delivery.DeliveryPositionType', verbose_name='Тип позиции поставки'),
        ),
    ]
