# Generated by Django 2.1.4 on 2019-02-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0024_auto_20190206_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryposition',
            name='delivery_position_type',
        ),
        migrations.DeleteModel(
            name='DeliveryPositionType',
        ),
    ]
