# Generated by Django 2.1.4 on 2019-02-06 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0025_auto_20190206_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPositionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Типа поставок может меняться от применения', max_length=100, verbose_name='Имя')),
                ('short', models.CharField(help_text='Краткое имя', max_length=5, unique=True, verbose_name='Короткое имя')),
                ('erp_link', models.CharField(blank=True, help_text='Ссылка на тип позиции поставки в ERP истемах, можно использовать как имя сервиса', max_length=40, null=True, verbose_name='Тип позиции поставки ERP')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryposition',
            name='delivery_position_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.DeliveryPositionType', verbose_name='Тип позиции поставки'),
        ),
    ]
