# Generated by Django 2.1.4 on 2019-02-02 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название кнопки')),
                ('short', models.CharField(help_text='Нужно вписать кнопку по стандарту', max_length=20, verbose_name='Кнопка')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Меню', max_length=50, verbose_name='Меню')),
                ('conteiner', models.BooleanField(help_text='если активно, то меню является контейнером для других меню', verbose_name='Является контейнером')),
                ('short', models.CharField(max_length=20, verbose_name='Краткое имя')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='URL Меню или метода')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rf.Menu', verbose_name='Вышестоящее меню')),
            ],
        ),
    ]
