# Generated by Django 2.1.4 on 2019-02-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rf', '0003_auto_20190202_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='keyid',
            field=models.CharField(blank=True, default='0', max_length=100, null=True, verbose_name='id Кнопки'),
        ),
    ]
