# Generated by Django 2.1.4 on 2018-12-04 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BussinesUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Это ячейка, склад или помещение?', max_length=50, verbose_name='Название складского комплекса')),
                ('nameERP', models.CharField(max_length=50, verbose_name='Связь с ERP')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('erpnumber', models.CharField(blank=True, max_length=50, verbose_name='Номер в ERP')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='Контакт')),
                ('tel', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('adress', models.CharField(blank=True, max_length=50, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Материал')),
                ('erpnumber', models.CharField(blank=True, max_length=50, verbose_name='Номер в ERP')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение')),
                ('type', models.CharField(choices=[('M', 'Материал'), ('S', 'Услуга')], max_length=50, verbose_name='Тип материала')),
                ('creator', models.ForeignKey(on_delete=models.SET('Юзер удален'), to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
        ),
        migrations.CreateModel(
            name='Quant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=5, max_digits=10, max_length=50, verbose_name='Количество')),
                ('bu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsbase.BussinesUnit', verbose_name='Бизнес юнит')),
                ('material', models.ForeignKey(on_delete=models.SET('Материал удален'), to='wmsbase.Material', verbose_name='Материал')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Идентификатор')),
                ('bu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsbase.BussinesUnit', verbose_name='Бизнес юнит')),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип юнита')),
            ],
        ),
        migrations.CreateModel(
            name='Uom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название ЕИ')),
                ('short', models.CharField(max_length=4, verbose_name='Краткое имя')),
                ('type', models.CharField(choices=[('M', 'Масса'), ('V', 'Обьем'), ('T', 'Время'), ('E', 'Количественный')], max_length=50, verbose_name='Тип ЕИ')),
                ('etalon', models.CharField(blank=True, choices=[('M', 'Масса'), ('V', 'Обьем'), ('T', 'Время'), ('E', 'Количественный')], help_text='Устанавливается в случае эталона', max_length=100, null=True, verbose_name='Является эталоном для')),
                ('value', models.DecimalField(decimal_places=5, help_text='Например, если эталон 1 КГ, в данная единица Г, то будет 0.001, если это эталон, то 1', max_digits=10, max_length=10, verbose_name='Множитель к эталону')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Помещение\\Склад\\Область действия\\участок склада\\ячейка с едиными правилами или свойстави', max_length=50, verbose_name='Складской обьект')),
                ('zero', models.BooleanField(help_text='Разрещение отрицательного запаса', verbose_name='Разрешение ОЗ')),
                ('short', models.CharField(max_length=4, verbose_name='Краткое имя')),
                ('bu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsbase.BussinesUnit', verbose_name='Бизнес юнит')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('short', models.CharField(max_length=4, verbose_name='Краткое имя')),
                ('bu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsbase.BussinesUnit', verbose_name='Бизнес юнит')),
            ],
        ),
        migrations.AddField(
            model_name='warehouseobject',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsbase.WarehouseObjectType', verbose_name='Тип обьекта'),
        ),
        migrations.AddField(
            model_name='unit',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='wmsbase.UnitType', verbose_name='Тип юнита'),
        ),
        migrations.AddField(
            model_name='unit',
            name='wo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsbase.WarehouseObject', verbose_name='Содержится в'),
        ),
        migrations.AddField(
            model_name='quant',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=models.SET('ЕИ Удалена'), to='wmsbase.Uom', verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='quant',
            name='wo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsbase.WarehouseObject', verbose_name='Содержится в'),
        ),
    ]
