# Generated by Django 2.1.4 on 2018-12-04 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wmsbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='type',
            field=models.ForeignKey(default=None, on_delete=models.SET('Тип юнита удален'), to='wmsbase.UnitType', verbose_name='Тип юнита'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='wmsbase.Unit', verbose_name='Вышестоящий юнит'),
        ),
    ]
