# Generated by Django 2.1.4 on 2018-12-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmsbase', '0005_auto_20181204_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=models.SET('Тип юнита удален'), to='wmsbase.UnitType', verbose_name='Тип юнита'),
        ),
    ]
