# Generated by Django 2.1.4 on 2018-12-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmsbase', '0008_warehouseobject_ident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseobject',
            name='ident',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Идентификатор'),
        ),
    ]
