# Generated by Django 2.1.4 on 2018-12-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmsbase', '0009_auto_20181204_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseobject',
            name='short',
            field=models.CharField(max_length=20, verbose_name='Краткое имя'),
        ),
    ]
