# Generated by Django 2.1.4 on 2018-12-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmsbase', '0010_auto_20181204_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseobjecttype',
            name='lowest',
            field=models.BooleanField(blank=True, help_text='Устанавливается на низжший уровень в иерархии обьектов например: Ячейка', null=True, verbose_name='Инд. низшего уровня'),
        ),
    ]
