# Generated by Django 2.1.4 on 2018-12-05 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wmsbase', '0011_warehouseobjecttype_lowest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('bu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsbase.BussinesUnit', verbose_name='Бизнес юнит')),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET(None), to='wmsbase.Client', verbose_name='Клиент')),
                ('order_creator', models.ForeignKey(on_delete=models.SET('Юзер удален'), related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('order_updater', models.ForeignKey(on_delete=models.SET('Юзер удален'), related_name='updater', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=5, max_digits=10, max_length=50, verbose_name='Количество')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('_creator', models.ForeignKey(on_delete=models.SET('Юзер удален'), related_name='create', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('_dest', models.ForeignKey(default=None, null=True, on_delete=models.SET(None), related_name='bin_inn', to='wmsbase.WarehouseObject', verbose_name='Ячейка назначения')),
                ('_source', models.ForeignKey(default=None, null=True, on_delete=models.SET(None), related_name='bin_out', to='wmsbase.WarehouseObject', verbose_name='Ячейка источник')),
                ('_updater', models.ForeignKey(on_delete=models.SET('Юзер удален'), related_name='update', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('bu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmsbase.BussinesUnit', verbose_name='Бизнес юнит')),
                ('material', models.ForeignKey(on_delete=models.SET('Материал удален'), to='wmsbase.Material', verbose_name='Материал')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.Order', verbose_name='Складской заказ')),
                ('uom', models.ForeignKey(null=True, on_delete=models.SET('ЕИ Удалена'), to='wmsbase.Uom', verbose_name='Единица измерения')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('_creator', '_updater', '_source', '_dest')},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('order_creator', 'order_updater')},
        ),
    ]
