# Generated by Django 2.1.4 on 2018-12-05 17:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wmsbase', '0011_warehouseobjecttype_lowest'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='_creator',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='_dest',
            new_name='dest',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='_source',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='_updater',
            new_name='updater',
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('creator', 'updater', 'source', 'dest')},
        ),
    ]
