# Generated by Django 2.1.4 on 2018-12-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('b', 'Пустой'), ('n', 'Новый)'), ('p', 'Выполняется'), ('d', 'Завершен')], default='Blank', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('b', 'Пустой'), ('n', 'Новый)'), ('p', 'Выполняется'), ('d', 'Завершен')], default='Blank', max_length=20, verbose_name='Статус'),
        ),
    ]
