# Generated by Django 2.1.4 on 2018-12-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_auto_20181213_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('b', 'Пустой'), ('n', 'Новый'), ('p', 'Выполняется'), ('d', 'Завершен')], default='Пустой', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('b', 'Пустой'), ('n', 'Новый'), ('p', 'Выполняется'), ('d', 'Завершен')], default='Пустой', max_length=20, verbose_name='Статус'),
        ),
    ]
