# Generated by Django 2.1.4 on 2019-01-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_auto_20181213_1851'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
    ]
