# Generated by Django 2.1.4 on 2019-01-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_auto_20190121_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dest',
            field=models.ForeignKey(default=None, on_delete=models.SET(None), related_name='bin_inn', to='wmsbase.WarehouseObject', verbose_name='Ячейка назначения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.ForeignKey(default=None, on_delete=models.SET(None), related_name='bin_out', to='wmsbase.WarehouseObject', verbose_name='Ячейка источник'),
        ),
    ]
