# Generated by Django 2.1.4 on 2019-02-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wmsbase', '0011_warehouseobjecttype_lowest'),
        ('operations', '0012_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='quant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wmsbase.Quant', verbose_name='Квант'),
        ),
        migrations.AddField(
            model_name='task',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wmsbase.Unit', verbose_name='Квант'),
        ),
    ]
