# Generated by Django 2.1.4 on 2019-02-06 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_auto_20190205_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dest',
            field=models.ForeignKey(default=None, on_delete=models.SET(None), related_name='bin_inn', to='wmsbase.WarehouseObject', verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='task',
            name='quant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wmsbase.Quant', verbose_name='Квант'),
        ),
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.ForeignKey(default=None, on_delete=models.SET(None), related_name='bin_out', to='wmsbase.WarehouseObject', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='task',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wmsbase.Unit', verbose_name='Квант'),
        ),
    ]
